oem: "Infinix"
device: "Infinix-X6852"
android_version: "15"
build_tag: "AP3A.240905.015.A2"
model: "Infinix NOTE 40 5G"

variants:
  - variant: "Global"
    android_version: "15"
    build_tag: "AP3A.240905.015.A2"
    product: "X6852-OP"
    incremental: "109156"

  - variant: "India"
    android_version: "15"
    build_tag: "AP3A.240905.015.A2"
    product: "X6852-IN"
    incremental: "123011"

  - variant: "Europe"
    android_version: "15"
    build_tag: "AP3A.240905.015.A2"
    product: "X6852-EU"
    incremental: "127002"
